"""Revision-directive rewriters that remove redundant operations from an autogenerated migration.

Alembic writes one ``op.drop_index()`` call for each index of a table that the same migration drops with
``op.drop_table()``.  PostgreSQL removes the indexes together with the table, so those calls do nothing.  PostgreSQL
also rejects ``DROP INDEX`` for a unique index that a foreign key depends on, so a redundant call can fail the
migration.  The Alembic cookbook documents a ``process_revision_directives`` hook that removes the calls.  This module
ships that hook as a ready-made :class:`~alembic.autogenerate.rewriter.Rewriter`.

The rewriter is opt-in.  Alembic's plugin system only registers comparators, so the rewriter cannot be enabled through
``autogenerate_plugins``.  Pass it to ``context.configure()`` yourself::

    from alembic_pg_autogen import skip_drop_index_for_dropped_tables

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=skip_drop_index_for_dropped_tables,
    )
"""

# pyright: reportUnusedFunction=false
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from alembic.autogenerate.rewriter import Rewriter
from alembic.operations import ops

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator
    from typing import Final, TypeAlias

    from alembic.operations.ops import MigrateOperation, OpContainer
    from alembic.runtime.migration import MigrationContext

    _TableKey: TypeAlias = tuple[str, str | None]

log = logging.getLogger(__name__)

skip_drop_index_for_dropped_tables: Final = Rewriter()
"""Remove each ``drop_index`` operation whose table the same migration function drops.

The rewriter processes ``upgrade()`` and ``downgrade()`` separately.  In each function it collects the tables that a
``DropTableOp`` removes, then discards every ``DropIndexOp`` that names one of those tables.  A ``ModifyTableOps``
container that becomes empty is discarded as well.  Every other operation stays in place.

Pass the rewriter as ``process_revision_directives`` to ``context.configure()``.  It is an Alembic
:class:`~alembic.autogenerate.rewriter.Rewriter`, so ``chain()`` combines it with a hook that you already use::

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=skip_drop_index_for_dropped_tables.chain(my_hook),
    )

``chain()`` returns a new rewriter and leaves this one unchanged.
"""


@skip_drop_index_for_dropped_tables.rewrites(ops.UpgradeOps)
@skip_drop_index_for_dropped_tables.rewrites(ops.DowngradeOps)
def _remove_drop_index_for_dropped_tables(
    _context: MigrationContext,
    _revision: object,
    directive: OpContainer,
) -> OpContainer:
    """Rewrite one ``UpgradeOps`` or ``DowngradeOps`` container in place and return it."""
    dropped = _dropped_tables(directive.ops)
    if dropped:
        directive.ops = list(_without_drop_index(directive.ops, dropped))
    return directive


def _dropped_tables(directives: Iterable[MigrateOperation]) -> set[_TableKey]:
    """Return the ``(table_name, schema)`` keys of every ``DropTableOp`` in *directives*."""
    return {(op.table_name, op.schema) for op in directives if isinstance(op, ops.DropTableOp)}


def _without_drop_index(directives: Iterable[MigrateOperation], dropped: set[_TableKey]) -> Iterator[MigrateOperation]:
    """Yield *directives* without the ``DropIndexOp`` entries that target a table in *dropped*.

    ``ModifyTableOps`` containers are filtered recursively, because autogenerate places the ``DropIndexOp`` for a
    dropped table inside such a container.  A container that ends up empty is not yielded.
    """
    for op in directives:
        if isinstance(op, ops.ModifyTableOps) and (op.table_name, op.schema) in dropped:
            op.ops = list(_without_drop_index(op.ops, dropped))
            if not op.ops:
                continue
        elif isinstance(op, ops.DropIndexOp) and (op.table_name, op.schema) in dropped:
            log.debug("Skipping drop_index %r: table %r is dropped in the same migration", op.index_name, op.table_name)
            continue
        yield op
