"""Opt-in ``process_revision_directives`` hooks that trim an autogenerated migration.

Alembic's plugin system only registers comparators, so these hooks cannot be enabled through ``autogenerate_plugins``.
Pass them to ``context.configure()`` yourself.
"""

# pyright: reportUnusedFunction=false
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from alembic.autogenerate.rewriter import Rewriter
from alembic.operations import ops

if TYPE_CHECKING:
    from collections.abc import Iterable, Iterator
    from typing import Final, TypeAlias

    from alembic.operations.ops import MigrateOperation, OpContainer
    from alembic.runtime.migration import MigrationContext

    _TableKey: TypeAlias = tuple[str, str | None]

log = logging.getLogger(__name__)

skip_drop_index_for_dropped_tables: Final = Rewriter()
"""Remove each ``drop_index`` whose table the same migration function drops.

This is the Alembic cookbook recipe "Don't emit DROP INDEX when the table is to be dropped as well", packaged as a
:class:`~alembic.autogenerate.rewriter.Rewriter`.  Pass it as ``process_revision_directives``, or ``chain()`` it with a
hook you already use::

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        process_revision_directives=skip_drop_index_for_dropped_tables,
    )
"""


@skip_drop_index_for_dropped_tables.rewrites(ops.UpgradeOps)
@skip_drop_index_for_dropped_tables.rewrites(ops.DowngradeOps)
def _remove_drop_index_for_dropped_tables(
    _context: MigrationContext,
    _revision: object,
    directive: OpContainer,
) -> OpContainer:
    """Rewrite one ``UpgradeOps`` or ``DowngradeOps`` container in place and return it."""
    dropped = _dropped_tables(directive.ops)
    if dropped:
        directive.ops = list(_without_drop_index(directive.ops, dropped))
    return directive


def _dropped_tables(directives: Iterable[MigrateOperation]) -> set[_TableKey]:
    """Return the ``(table_name, schema)`` keys of every ``DropTableOp`` in *directives*."""
    return {(op.table_name, op.schema) for op in directives if isinstance(op, ops.DropTableOp)}


def _without_drop_index(directives: Iterable[MigrateOperation], dropped: set[_TableKey]) -> Iterator[MigrateOperation]:
    """Yield *directives* without the ``DropIndexOp`` entries that target a table in *dropped*.

    ``ModifyTableOps`` containers are filtered recursively, because autogenerate places the ``DropIndexOp`` for a
    dropped table inside such a container.  A container that ends up empty is not yielded.
    """
    for op in directives:
        if isinstance(op, ops.ModifyTableOps) and (op.table_name, op.schema) in dropped:
            op.ops = list(_without_drop_index(op.ops, dropped))
            if not op.ops:
                continue
        elif isinstance(op, ops.DropIndexOp) and (op.table_name, op.schema) in dropped:
            log.debug("Skipping drop_index %r: table %r is dropped in the same migration", op.index_name, op.table_name)
            continue
        yield op
