"""Integration tests for the full autogenerate pipeline."""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from alembic.command import revision

from alembic_pg_autogen import IGNORED

if TYPE_CHECKING:
    from .alembic_helpers import AlembicProject


def _autogenerate(project: AlembicProject, **attrs: object) -> str:
    """Run autogenerate and return the generated migration file content."""
    cfg = project.config
    for key, value in attrs.items():
        cfg.attributes[key] = value

    script = revision(cfg, message="test", autogenerate=True)
    assert script is not None

    versions_dir = Path(cfg.get_main_option("script_location")) / "versions"  # pyright: ignore[reportArgumentType]
    migration_files = list(versions_dir.glob("*.py"))
    assert len(migration_files) == 1
    return migration_files[0].read_text()


@pytest.mark.integration
class TestAutogenerateCreateFunction:
    """5.1 — Autogenerate detects new functions."""

    def test_new_function_produces_create(self, alembic_project: AlembicProject):
        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {alembic_project.schema}.hello()
RETURNS text LANGUAGE sql AS $$ SELECT 'hi'::text $$"""

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl])

        assert "op.execute(" in content
        assert "CREATE OR REPLACE FUNCTION" in content
        assert "hello" in content


@pytest.mark.integration
class TestAutogenerateReplaceFunction:
    """5.2 — Autogenerate detects modified functions."""

    def test_modified_function_produces_replace(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.greet() RETURNS text
            LANGUAGE sql AS $$ SELECT 'hello'::text $$
        """)

        new_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.greet()
RETURNS text LANGUAGE sql AS $$ SELECT 'goodbye'::text $$"""

        content = _autogenerate(alembic_project, pg_functions=[new_ddl])

        assert "op.execute(" in content
        assert "goodbye" in content
        # Downgrade should contain the original definition
        assert "hello" in content or "DROP FUNCTION" in content


@pytest.mark.integration
class TestAutogenerateDropFunction:
    """5.3 — Autogenerate detects removed functions."""

    def test_dropped_function_produces_drop(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.obsolete() RETURNS void
            LANGUAGE sql AS $$ $$
        """)

        # Empty desired set with pg_functions=[] triggers the comparator but
        # declares no desired functions — existing ones should be dropped.
        content = _autogenerate(alembic_project, pg_functions=[])

        assert "DROP FUNCTION" in content
        assert "obsolete" in content


@pytest.mark.integration
class TestAutogenerateTriggers:
    """5.4 — Autogenerate detects trigger changes."""

    def test_new_trigger_produces_create(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE TABLE {schema}.events (id int)")
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.trg_fn() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$
        """)

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.trg_fn() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$"""
        trg_ddl = f"""\
CREATE TRIGGER notify_trg AFTER INSERT ON {schema}.events
FOR EACH ROW EXECUTE FUNCTION {schema}.trg_fn()"""

        content = _autogenerate(
            alembic_project,
            pg_functions=[fn_ddl],
            pg_triggers=[trg_ddl],
        )

        assert "CREATE TRIGGER" in content
        assert "notify_trg" in content

    def test_dropped_trigger_produces_drop(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE TABLE {schema}.events (id int)")
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.trg_fn() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$
        """)
        alembic_project.execute(f"""\
            CREATE TRIGGER old_trg AFTER INSERT ON {schema}.events
            FOR EACH ROW EXECUTE FUNCTION {schema}.trg_fn()
        """)

        # Declare the function but NOT the trigger → trigger should be dropped
        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.trg_fn() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$"""

        content = _autogenerate(
            alembic_project,
            pg_functions=[fn_ddl],
            pg_triggers=[],
        )

        assert "DROP TRIGGER" in content
        assert "old_trg" in content


@pytest.mark.integration
class TestAutogenerateDependencyOrdering:
    """5.5 — Operations appear in correct dependency order."""

    def test_function_creates_before_trigger_creates(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE TABLE {schema}.orders (id int)")

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.audit_fn() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$"""
        trg_ddl = f"""\
CREATE TRIGGER audit_trg AFTER INSERT ON {schema}.orders
FOR EACH ROW EXECUTE FUNCTION {schema}.audit_fn()"""

        content = _autogenerate(
            alembic_project,
            pg_functions=[fn_ddl],
            pg_triggers=[trg_ddl],
        )

        # In upgrade(), function CREATE should appear before trigger CREATE
        upgrade_match = re.search(r"def upgrade\(\).*?(?=def downgrade\(\))", content, re.DOTALL)
        assert upgrade_match is not None
        upgrade_body = upgrade_match.group(0)

        fn_pos = upgrade_body.find("audit_fn")
        trg_pos = upgrade_body.find("audit_trg")
        assert fn_pos != -1 and trg_pos != -1
        assert fn_pos < trg_pos, "Function CREATE should precede trigger CREATE in upgrade"


@pytest.mark.integration
class TestAutogenerateNoOp:
    """5.6 — No ops when state matches."""

    def test_matching_state_produces_no_ops(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.stable_fn() RETURNS void
            LANGUAGE sql AS $$ $$
        """)

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.stable_fn() RETURNS void
LANGUAGE sql AS $$ $$"""

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl])

        # upgrade() should just have "pass" — no ops
        upgrade_match = re.search(r"def upgrade\(\).*?(?=def downgrade\(\))", content, re.DOTALL)
        assert upgrade_match is not None
        assert "op.execute(" not in upgrade_match.group(0)


@pytest.mark.integration
class TestAutogenerateEmptyConfig:
    """5.7 — No errors when pg_functions/pg_triggers absent."""

    def test_no_config_produces_no_ops(self, alembic_project: AlembicProject):
        # Don't pass pg_functions or pg_triggers at all
        content = _autogenerate(alembic_project)

        # Should produce a valid migration with pass in upgrade/downgrade
        assert "def upgrade()" in content
        assert "def downgrade()" in content


@pytest.mark.integration
class TestAutogenerateUnparseableDDL:
    """Unparsable DDL in pg_functions or pg_triggers raises ValueError."""

    def test_unparseable_function_ddl_raises(self, alembic_project: AlembicProject):
        with pytest.raises(ValueError, match="Cannot parse function identity"):
            _autogenerate(alembic_project, pg_functions=["SELECT 1"])

    def test_unparseable_trigger_ddl_raises(self, alembic_project: AlembicProject):
        with pytest.raises(ValueError, match="Cannot parse trigger identity"):
            _autogenerate(alembic_project, pg_triggers=["SELECT 1"])

    def test_unparseable_view_ddl_raises(self, alembic_project: AlembicProject):
        with pytest.raises(ValueError, match="Cannot parse view identity"):
            _autogenerate(alembic_project, pg_views=["SELECT 1"])


@pytest.mark.integration
class TestAutogenerateCreateView:
    """Autogenerate detects new views."""

    def test_new_view_produces_create(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        view_ddl = f"CREATE OR REPLACE VIEW {schema}.hello_view AS SELECT 'hi'::text AS msg"

        content = _autogenerate(alembic_project, pg_views=[view_ddl])

        assert "op.execute(" in content
        assert "CREATE OR REPLACE VIEW" in content
        assert "hello_view" in content


@pytest.mark.integration
class TestAutogenerateReplaceView:
    """Autogenerate detects modified views."""

    def test_modified_view_produces_replace(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.greet_view AS SELECT 'hello'::text AS msg")

        new_ddl = f"CREATE OR REPLACE VIEW {schema}.greet_view AS SELECT 'goodbye'::text AS msg"

        content = _autogenerate(alembic_project, pg_views=[new_ddl])

        assert "op.execute(" in content
        assert "goodbye" in content


@pytest.mark.integration
class TestAutogenerateDropView:
    """Autogenerate detects removed views."""

    def test_dropped_view_produces_drop(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.obsolete_view AS SELECT 1 AS x")

        content = _autogenerate(alembic_project, pg_views=[])

        assert "DROP VIEW" in content
        assert "obsolete_view" in content


@pytest.mark.integration
class TestAutogenerateViewWithFunction:
    """Autogenerate handles views that reference functions."""

    def test_view_and_function_together(self, alembic_project: AlembicProject):
        schema = alembic_project.schema

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.get_val() RETURNS integer
LANGUAGE sql AS $$ SELECT 42 $$"""
        view_ddl = f"CREATE OR REPLACE VIEW {schema}.val_view AS SELECT {schema}.get_val() AS result"

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl], pg_views=[view_ddl])

        assert "get_val" in content
        assert "val_view" in content

    def test_function_created_before_view_in_upgrade(self, alembic_project: AlembicProject):
        schema = alembic_project.schema

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.order_fn() RETURNS integer
LANGUAGE sql AS $$ SELECT 1 $$"""
        view_ddl = f"CREATE OR REPLACE VIEW {schema}.order_view AS SELECT {schema}.order_fn() AS val"

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl], pg_views=[view_ddl])

        upgrade_match = re.search(r"def upgrade\(\).*?(?=def downgrade\(\))", content, re.DOTALL)
        assert upgrade_match is not None
        upgrade_body = upgrade_match.group(0)

        fn_pos = upgrade_body.find("order_fn")
        view_pos = upgrade_body.find("order_view")
        assert fn_pos != -1 and view_pos != -1
        assert fn_pos < view_pos, "Function CREATE should precede view CREATE in upgrade"


@pytest.mark.integration
class TestAutogenerateViewNoOp:
    """No ops when view state matches."""

    def test_matching_view_produces_no_ops(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.stable_view AS SELECT 1 AS x")

        view_ddl = f"CREATE OR REPLACE VIEW {schema}.stable_view AS SELECT 1 AS x"

        content = _autogenerate(alembic_project, pg_views=[view_ddl])

        upgrade_match = re.search(r"def upgrade\(\).*?(?=def downgrade\(\))", content, re.DOTALL)
        assert upgrade_match is not None
        assert "op.execute(" not in upgrade_match.group(0)


@pytest.mark.integration
class TestAutogenerateIgnoredObjectTypes:
    """``IGNORED`` leaves an object type unmanaged instead of dropping undeclared objects.

    Contrast with ``TestAutogenerateDropFunction`` / ``TestAutogenerateDropView``, where an empty sequence declares
    "there should be none of these" and existing objects are dropped.
    """

    def test_ignored_views_are_not_dropped(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.legacy_view AS SELECT 1 AS val")

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.hello()
RETURNS text LANGUAGE sql AS $$ SELECT 'hi'::text $$"""

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl], pg_views=IGNORED)

        assert "CREATE OR REPLACE FUNCTION" in content
        assert "DROP VIEW" not in content
        assert "legacy_view" not in content

    def test_ignored_functions_are_not_dropped(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.legacy_fn() RETURNS void
            LANGUAGE sql AS $$ $$
        """)

        view_ddl = f"CREATE OR REPLACE VIEW {schema}.hello_view AS SELECT 'hi'::text AS msg"

        content = _autogenerate(alembic_project, pg_views=[view_ddl], pg_functions=IGNORED)

        assert "CREATE OR REPLACE VIEW" in content
        assert "DROP FUNCTION" not in content
        assert "legacy_fn" not in content

    def test_ignored_triggers_are_not_dropped(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE TABLE {schema}.orders (id int)")
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.legacy_trg_fn() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$
        """)
        alembic_project.execute(f"""\
            CREATE TRIGGER legacy_trg AFTER INSERT ON {schema}.orders
            FOR EACH ROW EXECUTE FUNCTION {schema}.legacy_trg_fn()
        """)

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.legacy_trg_fn() RETURNS trigger
LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$"""

        content = _autogenerate(alembic_project, pg_functions=[fn_ddl], pg_triggers=IGNORED)

        assert "DROP TRIGGER" not in content
        assert "legacy_trg" not in content

    def test_all_ignored_produces_no_pg_ops(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.legacy_fn() RETURNS void
            LANGUAGE sql AS $$ $$
        """)
        alembic_project.execute(f"CREATE VIEW {schema}.legacy_view AS SELECT 1 AS val")

        content = _autogenerate(
            alembic_project,
            pg_functions=IGNORED,
            pg_triggers=IGNORED,
            pg_views=IGNORED,
        )

        upgrade_match = re.search(r"def upgrade\(\).*?(?=def downgrade\(\))", content, re.DOTALL)
        assert upgrade_match is not None
        assert "op.execute(" not in upgrade_match.group(0)


@pytest.mark.integration
class TestAutogenerateAbsentObjectTypes:
    """An absent configuration key leaves its object type unmanaged, exactly as an explicit ``IGNORED`` does.

    Contrast with ``TestAutogenerateDropView``, where an explicitly empty sequence declares "there should be none of
    these" and existing objects are dropped.
    """

    def test_absent_views_are_not_dropped(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.legacy_view AS SELECT 1 AS val")

        fn_ddl = f"""\
CREATE OR REPLACE FUNCTION {schema}.hello()
RETURNS text LANGUAGE sql AS $$ SELECT 'hi'::text $$"""

        # pg_views is never passed to context.configure()
        content = _autogenerate(alembic_project, pg_functions=[fn_ddl])

        assert "CREATE OR REPLACE FUNCTION" in content
        assert "DROP VIEW" not in content
        assert "legacy_view" not in content

    def test_absent_functions_and_triggers_are_not_dropped(self, alembic_project: AlembicProject):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE TABLE {schema}.orders (id int)")
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.legacy_trg_fn() RETURNS trigger
            LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$
        """)
        alembic_project.execute(f"""\
            CREATE TRIGGER legacy_trg AFTER INSERT ON {schema}.orders
            FOR EACH ROW EXECUTE FUNCTION {schema}.legacy_trg_fn()
        """)

        view_ddl = f"CREATE OR REPLACE VIEW {schema}.hello_view AS SELECT 'hi'::text AS msg"

        content = _autogenerate(alembic_project, pg_views=[view_ddl])

        assert "CREATE OR REPLACE VIEW" in content
        assert "DROP FUNCTION" not in content
        assert "DROP TRIGGER" not in content
        assert "legacy_trg" not in content

    def test_empty_sequence_still_drops_alongside_an_absent_key(self, alembic_project: AlembicProject):
        """The empty-sequence/absent distinction survives: ``[]`` declares "none", absence declares nothing."""
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.obsolete_view AS SELECT 1 AS x")
        alembic_project.execute(f"""\
            CREATE FUNCTION {schema}.untouched_fn() RETURNS void
            LANGUAGE sql AS $$ $$
        """)

        content = _autogenerate(alembic_project, pg_views=[])

        assert "DROP VIEW" in content
        assert "obsolete_view" in content
        assert "DROP FUNCTION" not in content
        assert "untouched_fn" not in content

    def test_misspelled_key_warns_and_leaves_type_unmanaged(
        self,
        alembic_project: AlembicProject,
        caplog: pytest.LogCaptureFixture,
    ):
        schema = alembic_project.schema
        alembic_project.execute(f"CREATE VIEW {schema}.legacy_view AS SELECT 1 AS val")

        view_ddl = f"CREATE OR REPLACE VIEW {schema}.wanted_view AS SELECT 2 AS val"

        with caplog.at_level(logging.WARNING, logger="alembic_pg_autogen.compare"):
            content = _autogenerate(alembic_project, pg_view=[view_ddl])

        assert "pg_view" in caplog.text
        assert "pg_views" in caplog.text
        assert "DROP VIEW" not in content
        assert "wanted_view" not in content
